### ISSUE TITLE
Support for GitLab CI/CD Components

### ISSUE THREAD

**Issue by scuba10steve** [openrewrite/rewrite-gitlab#1]
## What problem are you trying to solve?
For reference, [here's a blog post](https://about.gitlab.com/blog/2024/05/08/ci-cd-catalog-goes-ga-no-more-building-pipelines-from-scratch/) that announced CI / CD components becoming generally available.

Having the ability to translate from the older style `template` inclusion to components would be helpful.

Example for migration: [opentofu template -> opentofu component](https://gitlab.com/explore/catalog/components/opentofu#migrating-from-the-terraform-cicd-templates)

## Describe the situation before applying the recipe
This is not an extensive example, just a snippet
```yaml
include:
  - template: OpenTofu/Base.latest.gitlab-ci.yml
```

## Describe the situation after applying the recipe
```yaml
include:
  - component: $CI_SERVER_FQDN/components/opentofu/job-templates@~latest
    inputs:
      # The version must currently be specified explicitly as an input,
      # to find the correctly associated images. # This can be removed
      # once https://gitlab.com/gitlab-org/gitlab/-/issues/438275 is solved.
      version: ~latest
      opentofu_version: 1.6.0

```

## Have you considered any alternatives or workarounds?
Only alternative is to follow the aformentioned [migration guide(s)](https://gitlab.com/explore/catalog/components/opentofu#migrating-from-the-terraform-cicd-templates) that may or may not be available

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
Yes, I would be interested in helping contribute this recipe.

**Comment by timtebeek** [comment]
Great to see; `MergeYaml` should be able to help you here; here's a video going in depth on that topic: https://www.youtube.com/watch?v=MRHHGxh4rdU

**Comment by timtebeek** [comment]
Quick status and a plan for finishing this one off.

## Where we are today

The repo already has generic building blocks that cover most of what's needed:

- Templates: `AddTemplate`, `ChangeTemplate`, `RemoveTemplate`, `search.FindTemplate`
- Components: `AddComponent` (with `version` + `inputs`), `ChangeComponent`, `search.FindComponent`

What's **missing** is a dedicated migration recipe that turns a `template:` include into a `component:` include with `inputs` in a single step — i.e. the OpenTofu example in the issue description.

## Proposed recipe: `MigrateTemplateToComponent`

A declarative composite that chains `RemoveTemplate` + `AddComponent`, plus one concrete specialization per well-known GitLab migration (Terraform → OpenTofu is the obvious first one).

### Generic recipe (Java)

```java
public class MigrateTemplateToComponent extends Recipe {
    @Option(example = \"Terraform/Base.gitlab-ci.yml\") String oldTemplate;
    @Option(example = \"\$CI_SERVER_FQDN/components/opentofu/job-templates\") String newComponent;
    @Option(example = \"~latest\") String version;
    @Option(required = false, example = \"opentofu_version: 1.6.0\") @Nullable List<String> inputs;

    @Override public List<Recipe> getRecipeList() {
        return Arrays.asList(
            new RemoveTemplate(oldTemplate),
            new AddComponent(newComponent, version, inputs, null)
        );
    }
}
```

### Declarative specialization (YAML)

```yaml
---
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.gitlab.MigrateTerraformTemplateToOpenTofuComponent
displayName: Migrate GitLab Terraform template to OpenTofu component
description: >-
  Replace the deprecated \`Terraform/Base.latest.gitlab-ci.yml\` template
  include with the OpenTofu CI/CD component, per the GitLab catalog migration guide.
recipeList:
  - org.openrewrite.gitlab.MigrateTemplateToComponent:
      oldTemplate: Terraform/Base.latest.gitlab-ci.yml
      newComponent: \$CI_SERVER_FQDN/components/opentofu/job-templates
      version: ~latest
      inputs:
        - 'version: ~latest'
        - 'opentofu_version: 1.6.0'
```

## Test plan

- `MigrateTemplateToComponentTest` covering:
  - single-template file → replaced with component + inputs
  - multi-include file → only the targeted template is rewritten, siblings untouched
  - template not present → no-op
  - template with `@ref` suffix (handled by existing regex in `RemoveTemplate`)
  - no `inputs` provided → component added without an `inputs:` block
- `MigrateTerraformTemplateToOpenTofuComponentTest` using the exact before/after from this issue as a golden fixture
- Register the new specialization as an example in `examples.yml`

## Follow-ups (out of scope for the first PR, but worth tracking)

1. A handful of other well-known template → component migrations GitLab publishes (e.g. `SAST`, `Secret-Detection`, `Dependency-Scanning`), each as a thin declarative recipe on top of `MigrateTemplateToComponent`.
2. A `BestPractices`-style composite \"MigrateDeprecatedTemplatesToComponents\" once we have >1 specialization.
3. Consider a `FindMigratableTemplates` search recipe that flags any template include that has a known component equivalent — useful for inventorying repos before running the migration.

Happy to put up a PR for the generic recipe + the Terraform→OpenTofu specialization as step 1 if that sounds right.
