### ISSUE TITLE
`AddComponent` Recipe includes `inputs` even when they aren't specified.

### ISSUE THREAD

**Issue by scuba10steve** [openrewrite/rewrite-gitlab#22]
## What version of OpenRewrite are you using?
I am using

- rewrite-gitlab v0.13.0

## How are you running OpenRewrite?
I am using Moderne.io

## What is the smallest, simplest way to reproduce the problem?
Create a recipe that includes the `AddComponent` recipe, and leave the `inputs` field blank then at least run a dry run

## What did you expect to see?

```yaml
              include:
                - template: Gradle.gitlab-ci.yml
                - component: $CI_SERVER_FQDN/components/opentofu/full-pipeline@0.10.0
                  inputs:
                    version: 0.10.0
                    opentofu_version: 1.6.1
```

## What did you see instead?
```yaml
              include:
                - template: Gradle.gitlab-ci.yml
                - component: $CI_SERVER_FQDN/components/opentofu/full-pipeline@0.10.0
                  inputs:
                    version: 0.10.0
                    opentofu_version: 1.6.1
```

## Are you interested in [contributing a fix to OpenRewrite]
Yes, but may need assistance on this one.
