### ISSUE TITLE
Add 'RemoveTemplate' recipe

### ISSUE THREAD

**Issue by scuba10steve** [openrewrite/rewrite-gitlab#5]
## What problem are you trying to solve?
Introduce another 'building block' recipe for more complex scenarios

## Describe the situation before applying the recipe
```yaml
include:
  - template: Gradle.gitlab-ci.yml
  - template: Jobs/SAST.gitlab-ci.yml
```

## Describe the situation after applying the recipe
```yaml
include:
  - template: Gradle.gitlab-ci.yml
```

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
I will have an associated PR shortly :)
