### ISSUE TITLE
Add 'AddComponent' Recipe

### ISSUE THREAD

**Issue by scuba10steve** [openrewrite/rewrite-gitlab#8]
## What problem are you trying to solve?
This will help support the overall larger effort of #1, being a building-block for more complex recipes

## Describe the situation before applying the recipe

```yaml
include:
  - template: Jobs/SAST.gitlab-ci.yml
```

## Describe the situation after applying the recipe

```yaml
include:
  - template: Jobs/SAST.gitlab-ci.yml
  - component: $CI_SERVER_FQDN/components/opentofu/full-pipeline@0.10.0
    inputs:
      # The version must currently be specified explicitly as an input,
      # to find the correctly associated images. # This can be removed
      # once https://gitlab.com/gitlab-org/gitlab/-/issues/438275 is solved.
      version: 0.10.0
      opentofu_version: 1.6.1
```

## Are you interested in [contributing this recipe to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#adding-new-recipes)?
I'll have a PR shortly
